const express = require("express");
const app = express();
const cors = require("cors");
const bodyParser = require("body-parser");
const port = process.env.PORT || 9001;
const Registrationrouter = require("./Router/Registrationrouter");
const Signuprouter = require("./Router/Signuprouter");
const Cartdata = require("./Router/Cartdatarouter");
const Addtocart = require("./Router/Addtocart");
const Cartlistrouter = require("./Router/Cartlistrouter");
const Quantityrouter = require("./Router/Quantityrouter");
const Deleteitemsrouter = require("./Router/Deleteitemsrouter");
const Deletetokenrouter = require("./Router/Deletetokenrouter");
const Verifytokenrouter = require("./Router/verifytokenrouter");
const Forgotpasswordrouter = require("./Router/Forgotpasswordrouter");
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
require("./Database/Connection");
app.use("/userssignin", Registrationrouter);
app.use("/signup", Signuprouter);
app.use("/cartdata", Cartdata);
app.use("/addcart", Addtocart);
app.use("/cartlist", Cartlistrouter);
app.use("/quantity", Quantityrouter);
app.use("/deletecartitem", Deleteitemsrouter);
app.use("/deletetoken", Deletetokenrouter);
app.use("/verifytoken", Verifytokenrouter);
app.use("/update", Forgotpasswordrouter);
app.listen(port, () => {
  console.log("server is listening at port port " + port);
});
